[tool.poetry]
name = "rozetka-fastapi"
version = "0.1.0"
description = ""
authors = ["Alexey Rubaseff <alexey.rubasheff@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.4"
global_logger = "^0.4.2"
influxdb-client = {extras = ["async"], version = "^1.45.0"}
aiohttp-retry = "^2.8.3"
cashews = {extras = ["redis"], version = "^7.2.0"}
pydantic = "^2.8.2"
python-dotenv = "^1.0.1"
uvicorn = "^0.30.6"


[tool.poetry.group.dev.dependencies]
poetry = "^1.8.3"
ruff = "^0.6.1"
pre-commit = "^3.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
